
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  attorneys-api:
    image: attorney
    build:
      context: .
      dockerfile: src/Attorneys/Dockerfile
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=attorneysdb;User=sa;Password=Your_password123;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__Key: "ptVV6RdmjNiDGZBoV9NN0Km6FIockEtZVCzOnFP3wus="
      Jwt__Issuer: "http://localhost:5000"
      Jwt__Audience: "http://localhost:5000"
      Jwt__ExpiryMinutes: 60
    ports:
      - "8080:80"

